dist: xenial
language: minimal
#addons:
#    apt:
#      packages:
#        - qemu
#        - qemu-user-static
#        - binfmt-support
services:
    - docker
env:
    - NODE_VERSION=arm32v7/node:12-bullseye
    - NODE_VERSION=arm32v7/node:14-bullseye
    - NODE_VERSION=arm32v7/node:16-bullseye
    - NODE_VERSION=arm32v7/node:17-bullseye
    - NODE_VERSION=arm64v8/node:12-bullseye
    - NODE_VERSION=arm64v8/node:14-bullseye
    - NODE_VERSION=arm64v8/node:16-bullseye
    - NODE_VERSION=arm64v8/node:17-bullseye
install: skip
#before_script: docker run --rm --privileged multiarch/qemu-user-static:register
script:
    - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
    #- docker run -t --rm --entrypoint="/bin/sh" -v$(pwd):/root/app --workdir /root/app $NODE_VERSION -c "npm --version"
    - ./docker_build.sh $NODE_VERSION
